### ISSUE TITLE
TripDescriptor.schedule_relationship: 5 - Not a valid enum value (Javascript)

### ISSUE THREAD

**Issue by kayupeace** [MobilityData/gtfs-realtime-bindings#31]
**Full Error Message**: Illegal value for Message.Field .transit_realtime.TripDescriptor.schedule_relationship: 5 (not a valid enum value)
**Test Data:**  https://api.transport.nsw.gov.au/v1/gtfs/realtime/sydneytrains
**Example:** JavaScript/Node.js Sample
**Successful case:**  https://api.transport.nsw.gov.au/v1/gtfs/vehiclepos/sydneytrains
Comment: Year, it does support for the "vehicepos data set" test case as in the test file, but seems like this bindings does not support for the data set "realtime Sydney trains"

**Comment by barbeau** [comment]
@kayupeace Thanks for reporting this!  This is fixed in the gtfs-realtime .proto file in https://github.com/google/transit/commit/cabaec43e039f3425c50933ae6b227a720c74851, and we just need to do another release of gtfs-realtime-bindings to fix this, which we're working on.  I'll leave this issue open until we cut the new release.

**Comment by barbeau** [comment]
I just published v0.0.5 to NPM which should resolve this issue - could you please give this a try and see if it works?

If not, please re-open the issue.
