### ISSUE TITLE
Anyone using Ruby bindings?

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-realtime-bindings#44]
Is anyone in the community using the Ruby bindings in this repository?

I'm hitting some issues regenerating them from the gtfs-realtime.proto, as it seems proto2 files aren't officially supported by Google's Ruby protobuf compiler, and the bindings generated by a 3rd party app don't match the ones currently in the repo.  More at https://github.com/google/gtfs-realtime-bindings/pull/43/commits/3b2dd27cb2317ef84e67b037179e4f6fce37aa6d.

I've posted the same question to the [gtfs-realtime Google Group](https://groups.google.com/forum/#!topic/gtfs-realtime/RVtzlDvwKa4).

**Comment by drewda** [comment]
At @mapzen previously and now at @interline-io, we've used the Ruby RT bindings occasionally. They're useful because a lot of our other tooling is in Ruby.

However, our use is primarily for debugging on the command line and in small scripts. We have not put the Ruby bindings in to production use and probably would not do so for performance reasons. 

From my perspective, the Ruby bindings are nice to have but not necessary.

//cc @doublestranded

**Comment by nselikoff** [comment]
We use the Ruby bindings @omnimodal

**Comment by patrickbrownsync** [comment]
We are planning on using the Ruby bindings

**Comment by barbeau** [comment]
At this point we are deprecating support for the Ruby bindings in this library until the Google protobuf compiler officially supports proto2 for Ruby. We'd be glad to host links to 3rd party Ruby bindings maintained by others.
