### ISSUE TITLE
TripDescriptor hasScheduleRelationship incorrectly returns false

### ISSUE THREAD

**Issue by zachpepsin** [MobilityData/gtfs-realtime-bindings#57]
When working with the SEPTA GTFS-Rt feed, I found that the TripDescriptor hasScheduleRelationship() was returning false even for times when there were SCHEDULED schedule relationships present. SEPTA does not have any other statuses in their feed besides SCHEDULED, so that is all I was able to test. I'm unsure if this issue is present for other statuses.

**Comment by barbeau** [comment]
@zachpepsin Do you have a snippet of the feed in plain text you can share?

Off the top of my head I'm pretty sure this is one of the quirks of protocol buffers and the Java implementation, although from Googling now I can't find an explicit reference that says this. Because SCHEDULED is the default enum value for TripDescriptor, the bindings may just ignore it.

If you get the value, though, it should still return SCHEDULED, even if the SCHEDULED value doesn't appear in the message itself.

**Comment by zachpepsin** [comment]
@barbeau I pasted below a TripDescriptor object that I just pulled from SEPTA's feed.  You can also see that `hasScheduleRelationship()` returns `false` while the property returns `SCHEDULED`.  You may be right that a TripDescriptor wasn't provided, so it defaulted to `SCHEDULED`. yet the `hasScheduleRelationship()` still remains `false`.

![image](https://user-images.githubusercontent.com/6786291/75299738-daf72e80-5803-11ea-8ca0-7a52d6939131.png)

**Comment by barbeau** [comment]
Looking at http://www3.septa.org/gtfsrt/septarail-pa-us/Trip/rtTripUpdates.pb, here's a plain text version of a TripUpdate:

~~~
    {
      "id": "CHE_2720_V5_M",
      "trip_update": {
        "trip": {
          "trip_id": "CHE_2720_V5_M"
        },
        "stop_time_update": [
          {
            "stop_sequence": 35,
            "arrival": {
              "delay": 120,
              "uncertainty": 300
            },
            "stop_id": "90406"
          }
        ],
        "timestamp": 1582727280
      }
    },
~~~

So yes, it looks like they aren't populating the `schedule_relationship` field in the protocol buffer message.

So this is behaving as expected for protocol buffer bindings - `hasScheduleRelationship()` returns `false` because the original message didn't contain the field, but if you get the schedule relationship from the object it will still return the default value of SCHEDULED, because the default value if the field isn't populated is SCHEDULED.

This is just how Google's protocol buffer compiler works - you can read more about enumerations in protocol buffers here:
https://developers.google.com/protocol-buffers/docs/proto#enum

**Comment by zachpepsin** [comment]
Thans @barbeau!  Is this something you think is worth mentioning to SEPTA or do you think it's fine for them to not set the ScheduleRelationship and assume the default enum?

**Comment by barbeau** [comment]
@zachpepsin My personal opinion is that explicitly specifying the field is better than leaving it empty and having consumers assume the default. But if they are going to put energy into updating their feed my guess is that there are probably higher priority items they could be tackling.
